### ISSUE TITLE
Can we have separate argument for Failed testcases in show_results.py

### ISSUE THREAD

**Issue by naveen538** [ppc64le/sls-tool#18]
Having separate argument for Failed testcases would be helpful.
Ultimately our goal is to fix the issues from failed testcases.

**Comment by manjuhr1** [comment]
Fixed.

fail,conf,brok,skip -t       : shows all test results
./show_results.py -t fail  :   shows the failed tests
./show_results.py -t fail,brok : shows failed and broken tests
./show_results.py -t fail,conf,brok,skip : shows fail,conf,brok,skip

Thanks,
Manju
