### ISSUE TITLE
Showing Reason for test failure along with results would make test analysis easy. 

### ISSUE THREAD

**Issue by naveen538** [ppc64le/sls-tool#22]
Fetched this data from html-logs, Is there any way to view failure reason of testcase from html-logs?

puset_base_ops 65 TFAIL: cpuset.mems: Test result -  Expected string - "0-2"
cpuset_base_ops 67 TFAIL: cpuset.mems: Test result -  Expected string - "0-1"
cpuset_base_ops 153 TFAIL: Attaching Task Test failed!! cpus - "0", mems - "0", Expect - "0", Fact - "". (0 - Attach Success, 1 - Attach Fail)
cpuset_memory 1 TFAIL: set general group parameter failed.
cpuset_memory 3 TFAIL: set general group parameter failed.

**Comment by naveen538** [comment]
Fetched this data from html-logs, Is there any way to fetch failure reason of testcase from html-logs?

puset_base_ops 65 TFAIL: cpuset.mems: Test result -  Expected string - "0-2"
cpuset_base_ops 67 TFAIL: cpuset.mems: Test result -  Expected string - "0-1"
cpuset_base_ops 69 TFAIL: cpuset.mems: Test result -  Expected string - "0"
cpuset_base_ops 153 TFAIL: Attaching Task Test failed!! cpus - "0", mems - "0", Expect - "0", Fact - "". (0 - Attach Success, 1 - Attach Fail)
cpuset_memory 1 TFAIL: set general group parameter failed.
cpuset_memory 3 TFAIL: set general group parameter failed.

Expecting Reason of failure in Test Results.
<Testcase> <Result> <Reason>
<cpuset_memory> <FAIL> <set general group parameter failed>

**Comment by naveen538** [comment]
Expecting Reason of failure in Test Results.
<Testcase> <Result> <Reason>
<cpuset_memory> <FAIL> <set general group parameter failed>

**Comment by naveen538** [comment]
Fetched this data from html-logs, Is there any way to fetch failure reason of testcase from html-logs?

puset_base_ops 65 TFAIL: cpuset.mems: Test result -  Expected string - "0-2"
cpuset_base_ops 67 TFAIL: cpuset.mems: Test result -  Expected string - "0-1"
cpuset_base_ops 69 TFAIL: cpuset.mems: Test result -  Expected string - "0"
cpuset_base_ops 153 TFAIL: Attaching Task Test failed!! cpus - "0", mems - "0", Expect - "0", Fact - "". (0 - Attach Success, 1 - Attach Fail)
cpuset_memory 1 TFAIL: set general group parameter failed.
cpuset_memory 3 TFAIL: set general group parameter failed.

Expecting Reason of failure in Test Results.
[Testcase]  [Result]  [Reason]
[cpuset_memory]  [FAIL]  [set general group parameter failed]

**Comment by naveen538** [comment]
Can we maintain LTP logs separately to analyse test runs.

**Comment by manjuhr1** [comment]
The LTP LOGS are being saved on the VM at :  /opt/ltp/output   and /opt/ltp/results

**Comment by manjuhr1** [comment]
As discussed on slack,  the ltp logs are saved under /opt/ltp/output . So closing this issue.

Thanks,
Manju
