### ISSUE TITLE
Enable support to tests VPMEM, PMEM, NVDIMM by creating dax mounted filesystems

### ISSUE THREAD

**Issue by manjuhr1** [ppc64le/sls-tool#37]
- Change FS creation code in common_sls.py to support dax mounted silesystem for VPMEM,PMEM or nvdimm devices.

**Comment by priyama2** [comment]
https://github.com/ppc64le/sls-tool/pull/52

**Comment by manjuhr1** [comment]
Enhanced via : https://github.com/ppc64le/sls-tool/pull/54
