### ISSUE TITLE
Categorize the SLS end status 

### ISSUE THREAD

**Issue by manjuhr1** [ppc64le/sls-tool#39]
Update end STATUS of SLS run as following:
1. COMPLETED : For successful run
2. ABORTED: STOPPED_BY_OS : if run stopped by OS signal/crash/OOM
3. ABORTED: STOPPED_BY_USER : if user kills SLS via stop_sls.py

**Comment by manjuhr1** [comment]
Edit go_sls.py and stop_sls.py to update REPORT['RESULTS']['STATUS'] accordingly

**Comment by chetjain** [comment]
Pull requested through 
https://github.com/ppc64le/sls-tool/pull/47
