### ISSUE TITLE
Cap NFS test iterations to 10

### ISSUE THREAD

**Issue by manjuhr1** [ppc64le/sls-tool#40]
NFS tests are taking more time to execute, so restrict number of iterations for NFS tests to maximum 10

**Comment by manjuhr1** [comment]
Edit go_sls.py to cap NFS tests as like Network tests

**Comment by chetjain** [comment]
@manjuhr1 
@manjuhr1 
I would propose the following change in go_sls.py

    478                         if re.search(suite_iter[0], os.environ['NFS_LIST'], re.M):
    479                                 if suite_iter[1] > 10:
    480                                     suite_iter[1] = GetRandom(10, 1)

    516                         if re.search(suite_iter[0], os.environ['NFS_LIST'], re.M):
    517                                 if suite_iter[1] > 10:
    518                                         suite_iter[1] = GetRandom(10, 1)

Unlike what you have for n/w,  suite_iter[1] = 10, will hardcode the ITERATIONS to 10 and not float b/w 1 to 10.
Let me know, if you agree

**Comment by manjuhr1** [comment]
> Unlike what you have for n/w, suite_iter[1] = 10, will hardcode the ITERATIONS to 10 and not float b/w 1 to 10.
> Let me know, if you agree

Yes, between 1 to 10 is more suitable.
